//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebFiler.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebFiler.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Accessed.
        /// </summary>
        internal static string Accessed {
            get {
                return ResourceManager.GetString("Accessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        internal static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to border-collapse.
        /// </summary>
        internal static string BorderCollapse {
            get {
                return ResourceManager.GetString("BorderCollapse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to create the table..
        /// </summary>
        internal static string CantCreateTable {
            get {
                return ResourceManager.GetString("CantCreateTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to collapse.
        /// </summary>
        internal static string Collapse {
            get {
                return ResourceManager.GetString("Collapse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content-Disposition.
        /// </summary>
        internal static string ContentDisposition {
            get {
                return ResourceManager.GetString("ContentDisposition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to attachment; filename={0}.
        /// </summary>
        internal static string ContentDispositionAttachment {
            get {
                return ResourceManager.GetString("ContentDispositionAttachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/octet-stream.
        /// </summary>
        internal static string ContentType {
            get {
                return ResourceManager.GetString("ContentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div id=&quot;copyright&quot;&gt;&lt;label id=&quot;title&quot;&gt;WebFiler&lt;/label&gt; Copyright &amp;copy; 2010, &lt;a href=&quot;http://www.merrens.com/&quot; target=&quot;_blank&quot;&gt;MWM&lt;/a&gt;. All Rights Reserved. Version {0}&lt;/div&gt;.
        /// </summary>
        internal static string Copyright {
            get {
                return ResourceManager.GetString("Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to copyright.
        /// </summary>
        internal static string Copyright_CSS {
            get {
                return ResourceManager.GetString("Copyright_CSS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure that you want to delete {0}?.
        /// </summary>
        internal static string DeleteMessage {
            get {
                return ResourceManager.GetString("DeleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filer.aspx?r={0}.
        /// </summary>
        internal static string DeleteUrl {
            get {
                return ResourceManager.GetString("DeleteUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0 bytes.
        /// </summary>
        internal static string FFS0 {
            get {
                return ResourceManager.GetString("FFS0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:##.##} bytes.
        /// </summary>
        internal static string FFSB {
            get {
                return ResourceManager.GetString("FFSB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:##.##} gb.
        /// </summary>
        internal static string FFSGB {
            get {
                return ResourceManager.GetString("FFSGB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:##.##} kb.
        /// </summary>
        internal static string FFSKB {
            get {
                return ResourceManager.GetString("FFSKB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:##.##} mb.
        /// </summary>
        internal static string FFSMB {
            get {
                return ResourceManager.GetString("FFSMB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File is read only.
        /// </summary>
        internal static string FileIsReadOnly {
            get {
                return ResourceManager.GetString("FileIsReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filer.aspx?x=x&amp;o={0}.
        /// </summary>
        internal static string FileOpen {
            get {
                return ResourceManager.GetString("FileOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5px.
        /// </summary>
        internal static string FivePX {
            get {
                return ResourceManager.GetString("FivePX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to folder.
        /// </summary>
        internal static string Folder {
            get {
                return ResourceManager.GetString("Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find &apos;{0}&apos;&lt;br/&gt;Please Refresh or alter the &apos;Root&apos; value in &apos;Web.config&apos;..
        /// </summary>
        internal static string FolderNotFound {
            get {
                return ResourceManager.GetString("FolderNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ...
        /// </summary>
        internal static string FolderUpText {
            get {
                return ResourceManager.GetString("FolderUpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x.
        /// </summary>
        internal static string IsReadOnly {
            get {
                return ResourceManager.GetString("IsReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to javascript:if(confirm(&apos;{0}&apos;) == false) return false;.
        /// </summary>
        internal static string JSConfirm {
            get {
                return ResourceManager.GetString("JSConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Modified.
        /// </summary>
        internal static string Modified {
            get {
                return ResourceManager.GetString("Modified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}\{1}.
        /// </summary>
        internal static string NewObjectPath {
            get {
                return ResourceManager.GetString("NewObjectPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to onclick.
        /// </summary>
        internal static string OnClick {
            get {
                return ResourceManager.GetString("OnClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to padding-right.
        /// </summary>
        internal static string PaddingRight {
            get {
                return ResourceManager.GetString("PaddingRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..
        /// </summary>
        internal static string Period {
            get {
                return ResourceManager.GetString("Period", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WebFiler.Images.delete.png.
        /// </summary>
        internal static string PNG_DELETE {
            get {
                return ResourceManager.GetString("PNG_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WebFiler.Images.file.png.
        /// </summary>
        internal static string PNG_FILE {
            get {
                return ResourceManager.GetString("PNG_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WebFiler.Images.folder.png.
        /// </summary>
        internal static string PNG_FOLDER {
            get {
                return ResourceManager.GetString("PNG_FOLDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WebFiler.Images.folder_up.png.
        /// </summary>
        internal static string PNG_FOLDER_UP {
            get {
                return ResourceManager.GetString("PNG_FOLDER_UP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WebFiler.Images.rename.png.
        /// </summary>
        internal static string PNG_RENAME {
            get {
                return ResourceManager.GetString("PNG_RENAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to f.
        /// </summary>
        internal static string QSF {
            get {
                return ResourceManager.GetString("QSF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to m.
        /// </summary>
        internal static string QSM {
            get {
                return ResourceManager.GetString("QSM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to o.
        /// </summary>
        internal static string QSO {
            get {
                return ResourceManager.GetString("QSO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to r.
        /// </summary>
        internal static string QSR {
            get {
                return ResourceManager.GetString("QSR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x.
        /// </summary>
        internal static string QSX {
            get {
                return ResourceManager.GetString("QSX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        internal static string Rename {
            get {
                return ResourceManager.GetString("Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename {0}.
        /// </summary>
        internal static string RenameLabel {
            get {
                return ResourceManager.GetString("RenameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filer.aspx?r={0}&amp;f={1}&amp;m=1.
        /// </summary>
        internal static string RenameUrl {
            get {
                return ResourceManager.GetString("RenameUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WFReturn.
        /// </summary>
        internal static string Return {
            get {
                return ResourceManager.GetString("Return", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RO.
        /// </summary>
        internal static string RO {
            get {
                return ResourceManager.GetString("RO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WFRoot.
        /// </summary>
        internal static string Root {
            get {
                return ResourceManager.GetString("Root", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}?r={1}.
        /// </summary>
        internal static string RootNavigate {
            get {
                return ResourceManager.GetString("RootNavigate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filer.aspx.
        /// </summary>
        internal static string RRHome {
            get {
                return ResourceManager.GetString("RRHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filer.aspx?r={0}&amp;f=&amp;m=2.
        /// </summary>
        internal static string RRNewFile {
            get {
                return ResourceManager.GetString("RRNewFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filer.aspx?r={0}&amp;f=&amp;m=3.
        /// </summary>
        internal static string RRNewFolder {
            get {
                return ResourceManager.GetString("RRNewFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filer.aspx?r={0}.
        /// </summary>
        internal static string RRRefresh {
            get {
                return ResourceManager.GetString("RRRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filer.aspx?r={0}&amp;f=&amp;m=4.
        /// </summary>
        internal static string RRUpload {
            get {
                return ResourceManager.GetString("RRUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        internal static string Size {
            get {
                return ResourceManager.GetString("Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;link rel=&quot;stylesheet&quot; text=&quot;text/css&quot; href=&quot;{0}&quot; /&gt;.
        /// </summary>
        internal static string STYLE_LINK {
            get {
                return ResourceManager.GetString("STYLE_LINK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WebFiler.CSS.Default.css.
        /// </summary>
        internal static string STYLES {
            get {
                return ResourceManager.GetString("STYLES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3px.
        /// </summary>
        internal static string ThreePX {
            get {
                return ResourceManager.GetString("ThreePX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WebFiler.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unknown.
        /// </summary>
        internal static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
    }
}
